In [1]:
1+1


2

In [ ]:
1+1

In [2]:
import numpy as np

In [4]:
lst=[1,2,3,4]
arr=np.array(lst)


In [5]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(4,)

In [10]:
arr1=np.array([[1,2,3],[4,5,6]])

In [12]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr1.shape

(2, 3)

In [18]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [19]:
arr1.dtype

dtype('int32')

In [25]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [32]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [37]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [40]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [45]:
np.linspace(1,20,40).reshape(8,5)

array([[ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795],
       [ 3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282],
       [ 8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026],
       [10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769],
       [13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513],
       [15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256],
       [18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ]])

In [47]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [55]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [63]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [64]:
print("Random number generation(Uniform distribution)")
np.random.rand(2,3)

Random number generation(Uniform distribution)


array([[0.23740896, 0.34926633, 0.17254435],
       [0.8076354 , 0.39457186, 0.87723953]])

In [67]:
print("random number following a normal distibution with mean=0 and std=1 ")
print(np.random.randn(2,3))


random number following a normal distibution with mean=0 and std=1 
[[ 0.24637871  0.8773278   0.41340624]
 [-0.11152918 -2.5571923   0.69764574]]


In [70]:
np.random.randint(1,100,(2,2))

array([[91, 42],
       [47, 46]])

In [72]:
arr=np.arange(0,11)

In [80]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [83]:
arr[-1:7:-1]

array([10,  9,  8])

In [92]:
arr1=np.random.randint(2,100,20).reshape(5,4)
arr1

array([[ 9, 32, 49, 90],
       [77, 12, 43, 20],
       [99,  6,  3, 83],
       [72, 93, 45, 70],
       [76, 40,  8, 18]])

In [103]:
arr1[2:5:2,0:5:3]

array([[99, 83],
       [76, 18]])

In [108]:
arr2=np.random.randint(1,100,(3,3,))
arr3=np.random.randint(20,200,(3,3))
arr2/arr3

array([[0.61728395, 1.10344828, 1.06666667],
       [0.5483871 , 0.14189189, 1.37313433],
       [0.53472222, 2.06060606, 1.0326087 ]])

In [110]:
np.sqrt(arr2)

array([[7.07106781, 8.        , 8.94427191],
       [8.24621125, 4.58257569, 9.59166305],
       [8.77496439, 8.24621125, 9.74679434]])

In [111]:
np.exp(arr3)

array([[1.50609731e+35, 1.54553894e+25, 3.73324200e+32],
       [7.12058633e+53, 1.88618081e+64, 1.25236317e+29],
       [3.45466066e+62, 2.14643580e+14, 9.01762841e+39]])

In [113]:
arr1=np.arange(1,100)

In [114]:
arr1[2:]=1000

In [115]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [116]:
np.dot(arr2,arr3)

array([[23506, 15012, 15398],
       [21360, 10088, 14971],
       [28349, 17665, 19071]])

: 

In [1]:

import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a=np.array([1,2,3,45,6,7,8,9])

In [4]:
a


array([ 1,  2,  3, 45,  6,  7,  8,  9])

In [5]:
np.ndim(a)

1

In [10]:
b=np.array([[1,2,3],[4,5,6]])

In [7]:
a=np.array([1,2,3])

In [8]:
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [12]:
a.ndim

1

In [13]:
b.ndim

2

In [14]:
c=np.array([[[1,2,3],[4,5,6]]])

In [15]:
c.shape

(1, 2, 3)

In [16]:
c.ndim

3

In [17]:
a

array([1, 2, 3])

In [18]:
a.reshape(1,3)

array([[1, 2, 3]])

In [19]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [20]:
a


array([1, 2, 3])

In [21]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
c

array([[[1, 2, 3],
        [4, 5, 6]]])

In [23]:

a.dtype

dtype('int32')

In [30]:
arr=np.array([1,2.3,4.5],dtype=int)

In [32]:
arr

array([1, 2, 4])

In [39]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [40]:
np.ones(4)

array([1., 1., 1., 1.])

In [42]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [43]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
np.random.random((1,5))

array([[0.23753335, 0.98410578, 0.60970644, 0.42831437, 0.72793169]])

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(2,9,5)

array([2, 7])

In [59]:
np.linspace(0.1,0.5,)

array([0.1       , 0.14444444, 0.18888889, 0.23333333, 0.27777778,
       0.32222222, 0.36666667, 0.41111111, 0.45555556, 0.5       ])

In [60]:
a=np.array([1,2,3,4])

In [65]:
b=np.array([7,8,9,10])

In [66]:
a+b

array([ 8, 10, 12, 14])

In [67]:
 b-a

array([6, 6, 6, 6])

In [68]:
a*b

array([ 7, 16, 27, 40])

In [70]:
b/a

array([7. , 4. , 3. , 2.5])

In [71]:
sum(a)

10

In [72]:
max(a)

4

In [73]:
min(b)

7

In [76]:
np.average(b)

8.5

In [77]:
np.diff(a)

array([1, 1, 1])

In [78]:
np.diff(b)

array([1, 1, 1])

In [79]:
np.prod(a)

24

In [80]:
np.mean(a)

2.5

In [81]:

np.floor(3.56)

3.0

In [83]:
np.ceil(3.1)

4.0

In [91]:
a=a.reshape(2,2)

In [90]:
b=b.reshape(2,2)

In [87]:
np.concatenate((a,b))

array([ 1,  2,  3,  4,  7,  8,  9, 10])

In [92]:
a


array([[1, 2],
       [3, 4]])

In [93]:
b

array([[ 7,  8],
       [ 9, 10]])

In [94]:
np.add(a,b)

array([[ 8, 10],
       [12, 14]])

In [95]:
np.dot(a,b)

array([[25, 28],
       [57, 64]])

In [96]:
a

array([[1, 2],
       [3, 4]])

In [97]:
a.T

array([[1, 3],
       [2, 4]])

In [98]:
def f(x): return x*x

In [99]:
f(a)

array([[ 1,  4],
       [ 9, 16]])

In [100]:
u=np.array([2,3,0])
v=np.array([3,1,2])

In [102]:
np.inner(u,v)

9

In [103]:
np.inner(u,2)

array([4, 6, 0])